sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t monjifz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true monjifz/react-test npm test

after_success:
  - docker build -t monjifz/multi-client ./client
  - docker build -t monjifz/multi-nginx ./nginx
  - docker build -t monjifz/multi-server ./server
  - docker build -t monjifz/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push monjifz/multi-client
  - docker push monjifz/multi-nginx
  - docker push monjifz/multi-server
  - docker push monjifz/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi-container-docker'
  env: 'Multicontainerdocker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-809325701924'
  bucket_path: 'multi-container-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

